from panda3d.core import loadPrcFile
from direct.actor.Actor import Actor

if __debug__:
    loadPrcFile('../config/Config.prc')

Phase3AnimList = (('neutral', 'neutral'), ('run', 'run'))
Phase3_5AnimList = (('walk', 'walk'),
                    ('teleport', 'teleport'),
                    ('book', 'book'),
                    ('jump', 'jump'),
                    ('running-jump', 'running-jump'),
                    ('jump-squat', 'jump-zstart'),
                    ('jump-idle', 'jump-zhang'),
                    ('jump-land', 'jump-zend'),
                    ('running-jump-squat', 'leap_zstart'),
                    ('running-jump-idle', 'leap_zhang'),
                    ('running-jump-land', 'leap_zend'),
                    ('pushbutton', 'press-button'),
                    ('throw', 'pie-throw'),
                    ('victory', 'victory-dance'),
                    ('sidestep-left', 'sidestep-left'),
                    ('conked', 'conked'),
                    ('cringe', 'cringe'),
                    ('wave', 'wave'),
                    ('shrug', 'shrug'),
                    ('angry', 'angry'),
                    ('tutorial-neutral', 'tutorial-neutral'),
                    ('left-point', 'left-point'),
                    ('right-point', 'right-point'),
                    ('right-point-start', 'right-point-start'),
                    ('give-props', 'give-props'),
                    ('give-props-start', 'give-props-start'),
                    ('right-hand', 'right-hand'),
                    ('right-hand-start', 'right-hand-start'),
                    ('duck', 'duck'),
                    ('sidestep-right', 'jump-back-right'),
                    ('periscope', 'periscope'))
Phase4AnimList = (('sit', 'sit'),
                  ('sit-start', 'intoSit'),
                  ('swim', 'swim'),
                  ('tug-o-war', 'tug-o-war'),
                  ('sad-walk', 'losewalk'),
                  ('sad-neutral', 'sad-neutral'),
                  ('up', 'up'),
                  ('down', 'down'),
                  ('left', 'left'),
                  ('right', 'right'),
                  ('applause', 'applause'),
                  ('confused', 'confused'),
                  ('bow', 'bow'),
                  ('curtsy', 'curtsy'),
                  ('bored', 'bored'),
                  ('think', 'think'),
                  ('battlecast', 'fish'),
                  ('cast', 'cast'),
                  ('castlong', 'castlong'),
                  ('fish-end', 'fishEND'),
                  ('fish-neutral', 'fishneutral'),
                  ('fish-again', 'fishAGAIN'),
                  ('reel', 'reel'),
                  ('reel-H', 'reelH'),
                  ('reel-neutral', 'reelneutral'),
                  ('pole', 'pole'),
                  ('pole-neutral', 'poleneutral'),
                  ('slip-forward', 'slip-forward'),
                  ('slip-backward', 'slip-backward'),
                  ('catch-neutral', 'gameneutral'),
                  ('catch-run', 'gamerun'),
                  ('catch-eatneutral', 'eat_neutral'),
                  ('catch-eatnrun', 'eatnrun'),
                  ('catch-intro-throw', 'gameThrow'),
                  ('swing', 'swing'),
                  ('pet-start', 'petin'),
                  ('pet-loop', 'petloop'),
                  ('pet-end', 'petend'),
                  ('scientistJealous', 'scientistJealous'),
                  ('scientistEmcee', 'scientistEmcee'),
                  ('scientistWork', 'scientistWork'),
                  ('scientistGame', 'scientistGame'))
Phase5AnimList = (('water-gun', 'water-gun'),
                  ('hold-bottle', 'hold-bottle'),
                  ('firehose', 'firehose'),
                  ('spit', 'spit'),
                  ('tickle', 'tickle'),
                  ('smooch', 'smooch'),
                  ('happy-dance', 'happy-dance'),
                  ('sprinkle-dust', 'sprinkle-dust'),
                  ('juggle', 'juggle'),
                  ('climb', 'climb'),
                  ('sound', 'shout'),
                  ('toss', 'toss'),
                  ('hold-magnet', 'hold-magnet'),
                  ('hypnotize', 'hypnotize'),
                  ('struggle', 'struggle'),
                  ('lose', 'lose'),
                  ('melt', 'melt'))
Phase5_5AnimList = (('takePhone', 'takePhone'),
                    ('phoneNeutral', 'phoneNeutral'),
                    ('phoneBack', 'phoneBack'),
                    ('bank', 'jellybeanJar'),
                    ('callPet', 'callPet'),
                    ('feedPet', 'feedPet'),
                    ('start-dig', 'into_dig'),
                    ('loop-dig', 'loop_dig'),
                    ('water', 'water'))
Phase6AnimList = (('headdown-putt', 'headdown-putt'),
                  ('into-putt', 'into-putt'),
                  ('loop-putt', 'loop-putt'),
                  ('rotateL-putt', 'rotateL-putt'),
                  ('rotateR-putt', 'rotateR-putt'),
                  ('swing-putt', 'swing-putt'),
                  ('look-putt', 'look-putt'),
                  ('lookloop-putt', 'lookloop-putt'),
                  ('bad-putt', 'bad-putt'),
                  ('badloop-putt', 'badloop-putt'),
                  ('good-putt', 'good-putt'))
Phase9AnimList = (('push', 'push'),)
Phase10AnimList = (('leverReach', 'leverReach'), ('leverPull', 'leverPull'), ('leverNeutral', 'leverNeutral'))
Phase12AnimList = ()


LegDict = {'s': '/models/char/tt_a_chr_dgs_shorts_legs_',
           'm': '/models/char/tt_a_chr_dgm_shorts_legs_',
           'l': '/models/char/tt_a_chr_dgl_shorts_legs_'}
TorsoDict = {
    'ss': '/models/char/tt_a_chr_dgs_shorts_torso_',
    'ms': '/models/char/tt_a_chr_dgm_shorts_torso_',
    'ls': '/models/char/tt_a_chr_dgl_shorts_torso_',
    'sd': '/models/char/tt_a_chr_dgs_skirt_torso_',
    'md': '/models/char/tt_a_chr_dgm_skirt_torso_',
    'ld': '/models/char/tt_a_chr_dgl_skirt_torso_'}

"""
HeadDict = {'dls': '/models/char/dogMM_Shorts-head-',
            'dss': '/models/char/dogMM_Skirt-head-',
            'dsl': '/models/char/dogSS_Shorts-head-',
            'dll': '/models/char/dogLL_Shorts-head-',
"""

HeadDict = {'c': '/models/char/cat-heads-',
            'h': '/models/char/horse-heads-',
            'm': '/models/char/mouse-heads-',
            'r': '/models/char/rabbit-heads-',
            'f': '/models/char/duck-heads-',
            'p': '/models/char/monkey-heads-',
            'b': '/models/char/bear-heads-',
            's': '/models/char/pig-heads-'}
EyelashDict = {'d': '/models/char/dog-lashes',
               'c': '/models/char/cat-lashes',
               'h': '/models/char/horse-lashes',
               'm': '/models/char/mouse-lashes',
               'r': '/models/char/rabbit-lashes',
               'f': '/models/char/duck-lashes',
               'p': '/models/char/monkey-lashes',
               'b': '/models/char/bear-lashes',
               's': '/models/char/pig-lashes'}
DogMuzzleDict = {'dls': '/models/char/dogMM_Shorts-headMuzzles-',
                 'dss': '/models/char/dogMM_Skirt-headMuzzles-',
                 'dsl': '/models/char/dogSS_Shorts-headMuzzles-',
                 'dll': '/models/char/dogLL_Shorts-headMuzzles-'}

toonSpeciesTypes = ['d',
                    'c',
                    'h',
                    'm',
                    'r',
                    'f',
                    'p',
                    'b',
                    's']

toonHeadTypes = ['dls',
                 'dss',
                 'dsl',
                 'dll',
                 'cls',
                 'css',
                 'csl',
                 'cll',
                 'hls',
                 'hss',
                 'hsl',
                 'hll',
                 'mls',
                 'mss',
                 'rls',
                 'rss',
                 'rsl',
                 'rll',
                 'fls',
                 'fss',
                 'fsl',
                 'fll',
                 'pls',
                 'pss',
                 'psl',
                 'pll',
                 'bls',
                 'bss',
                 'bsl',
                 'bll',
                 'sls',
                 'sss',
                 'ssl',
                 'sll']

toonTorsoTypes = ['ss',
                  'ms',
                  'ls',
                  'sd',
                  'md',
                  'ld',
                  's',
                  'm',
                  'l']

toonLegTypes = ['s', 'm', 'l']

allColorsList = [(1.0, 1.0, 1.0, 1.0),
                 (0.96, 0.69, 0.69, 1.0),
                 (0.93, 0.26, 0.28, 1.0),
                 (0.86, 0.40, 0.41, 1.0),
                 (0.71, 0.23, 0.43, 1.0),
                 (0.57, 0.44, 0.16, 1.0),
                 (0.64, 0.35, 0.26, 1.0),
                 (0.99, 0.69, 0.51, 1.0),
                 (0.83, 0.5, 0.29, 1.0),
                 (0.99, 0.48, 0.16, 1.0),
                 (0.99, 0.89, 0.32, 1.0),
                 (0.99, 0.95, 0.59, 1.0),
                 (0.85, 0.93, 0.49, 1.0),
                 (0.55, 0.82, 0.32, 1.0),
                 (0.24, 0.74, 0.51, 1.0),
                 (0.30, 0.96, 0.4, 1.0),
                 (0.43, 0.9, 0.83, 1.0),
                 (0.34, 0.82, 0.95, 1.0),
                 (0.19, 0.56, 0.77, 1.0),
                 (0.55, 0.58, 0.87, 1.0),
                 (0.28, 0.32, 0.72, 1.0),
                 (0.46, 0.37, 0.82, 1.0),
                 (0.54, 0.28, 0.75, 1.0),
                 (0.72, 0.47, 0.85, 1.0),
                 (0.89, 0.61, 0.9, 1.0),
                 (0.7, 0.7, 0.8, 1.0),
                 (0.3, 0.3, 0.35, 1.0),
                 (0.0, 0.63, 0.25, 1.0),
                 (0.67, 0.92, 1.0, 1.0),
                 (0.98, 0.89, 0.74, 1.0),
                 (0.74, 1.0, 0.84, 1.0),
                 (0.47, 0.44, 0.44, 1.0),
                 (0.99, 0.25, 0.39, 1.0),
                 (0.81, 0.7, 0.23, 1.0),
                 (0.74, 0.75, 0.76, 1.0),
                 (1.0, 0.63, 0.26, 1.0),
                 (0.0, 0.4, 0.64, 1.0),
                 (0.86, 0.07, 0.23, 1.0),
                 (0.0, 0.63, 0.51, 1.0),
                 (0.8, 0.49, 0.19, 1.0)]


playerBody = Actor({
    # model dict
    'suit': 'phase_3.5/models/char/suitB-mod.bam'},

    # anim dict
    {'suit': {'neutral': 'phase_4/models/char/suitB-neutral.bam',
              'walk': 'phase_4/models/char/suitB-walk.bam'}}
)

playerHead = {'sun': 'phase_4/models/props/sun.bam'}

Goon = Actor({
    # model dict
    'body': 'phase_9/models/char/Cog_Goonie-zero.bam'},

    # anim dict
    {'body': {'walk': 'phase_9/models/char/Cog_Goonie-walk.bam'}}
)
